### ISSUE TITLE
java.lang.NoSuchMethodErro

### ISSUE THREAD

**Issue by guxuanyu** [Andy671/Dachshund-Tab-Layout#1]
hello andy671
I use it with an error
what is the solution
error:
```
Process: com.example.ganger.dmzjapp, PID: 24343
                                                                            java.lang.NoSuchMethodError: No super method setupWithViewPager(Landroid/support/v4/view/ViewPager;Z)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/data/com.example.ganger.dmzjapp/files/instant-run/dex/slice-com.android.support-design-23.3.0_885fe9c4b8444b33318faa2144462abf1840cd46-classes.dex)
                                                                                at com.kekstudio.dachshundtablayout.DachshundTabLayout.setupWithViewPager(DachshundTabLayout.java:122)
                                                                                at com.kekstudio.dachshundtablayout.DachshundTabLayout.setupWithViewPager(DachshundTabLayout.java:117)
                                                                                at com.example.ganger.dmzjapp.MainActivity.onCreate(MainActivity.java:158)
                                                                                at android.app.Activity.performCreate(Activity.java:6237)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
````

code:
```
 pageAdapter=new MyPageAdapter(getSupportFragmentManager(),titles,fs);
        viewPager.setAdapter(pageAdapter);

        dachshundTabLayout= (DachshundTabLayout) findViewById(R.id.tab_layout);
        dachshundTabLayout.setupWithViewPager(viewPager);
```

**Comment by guxuanyu** [comment]
DachshundTabLayout.class
```
public void setupWithViewPager(@Nullable ViewPager viewPager) {
        this.setupWithViewPager(viewPager, true);
    }

    public void setupWithViewPager(@Nullable ViewPager viewPager, boolean autoRefresh) {
        super.setupWithViewPager(viewPager, autoRefresh);
        if(viewPager != null && viewPager != this.viewPager) {
            viewPager.removeOnPageChangeListener(this);
            viewPager.addOnPageChangeListener(this);
        }

    }
```
TabLyout.java    we can see this method has no second Boolean param  Why?
```
public void setupWithViewPager(@Nullable final ViewPager viewPager) {
        if (mViewPager != null && mPageChangeListener != null) {
            // If we've already been setup with a ViewPager, remove us from it
            mViewPager.removeOnPageChangeListener(mPageChangeListener);
        }

        if (viewPager != null) {
.......
```

**Comment by guxuanyu** [comment]
ok ,maybe we should use api version 25+,i solved it
